workshop/madrid2019.md

Hi Robert,
Here my first draft of the madrid workshop wiki page. As you know, this is not definitive but I would like to try whether the page works as intended

first draft madrid workshop markdown file

---

tutorial/human_ecog.md

human ecog tutorial update

---

tutorial/human_ecog.md

human ecog tutorial: inserted video and figure links

human ecog tutorial: inserted video and figure links

---

workshop/madrid2019.md

let's see whether the Madrid page works: I just deleted accents and special characters

special characters and accents deleted

---

workshop/madrid2019/tutorial_erp.md

bullet points, figures, adding a "see also" section

update formatting of tutorial_erp

---

workshop/madrid2019/tutorial_freq.md

I moved and adapted the multitapers explanation plus some small fixes

shortening freq tutorial

---

workshop/madrid2019/tutorial_cleaning.md

Here I tried to clarify concepts and to link the sections to the de Cheveigne paper more direclty

improving explanations cleaning tutorial

---

tutorial/sourcemodel.md

I checked all parts of the tutorial related to creation of a surface-based source model and all work (at the DCCN) with the few minor adjustments I made.

Proposed update to tutorial

---

workshop/oslo2019.md

Added some basic information to oslo.md

added where, when and who + tentative programme

---

faq/how_can_i_process_continuous_data_without_triggers.md

Just two small typo fixes in `how_can_i_process_continuous_data_without_triggers` :)

small typo fixes in `how_can_i_process_continuous_data_without_triggers`

---

index.md

news update

---

tutorial/preprocessing_erp.md

Fixed two links and two typos.

small link and typo fixes to tutorial/preprocessing_erp

---

workshop/davis2019.md

before, all text was concatenated, now it's in a table format

formatting change

---

tutorial/epilepsy.md

Updated the epilepsy tutorial with clinical information, use of AnyWave to screen data, analysis of the Elekta dataset.
Still to add: images

Wittonc patch 1

---

tutorial/epilepsy.md

Also some other minor clarifications of the clinical information

Updated both tutorials to include images

---

workshop/baci2017/forwardproblem.md

It only worked when passing the mesh. This is with the head version of Fieldtrip.

The ft_plot_mesh did not work when passing the headmodel

---

workshop/oslo2019/1_introduction_to_FieldTrip_and_EEG.md

More can/will be added, but I would like to see how it looks

first draft of a tutorial

---

workshop/oslo2019/timefrequency.md

... and another round - the updated links from the last PR were still broken.

Fix for figures in TFR tutorial Oslo 2019

---

workshop/oslo2019.md

Also feel free to just remove the links if you prefer

adding information about when lecture links will be up

---

example/connectivity_conditional_granger.md

Formatting is not the most beautiful, but I hope the script still contributes.

New example script for conditional Granger causality

---

_includes/shared/particular_data.md
getting_started/nicolet.md

If the [pull request in the fieldtrip repo that finalizes the Nicolet reading](https://github.com/fieldtrip/fieldtrip/pull/302) is accepted, then this pull request will update the documentation to reflect that Nicolet files can be read.

Added info on Nicolet EEG format

---

development/guideline/documentation.md

fix typo so that it correctly points to existing img file

fix typo in file name

---

tutorial/nirs_multichannel.md

Otherwise after copy&paste:
Error: File: test_nirs_multichannel.m Line: 55 Column: 32
The input character is not valid in MATLAB statements or expressions.

fix - correcting transpose character 

---

_posts/2020-03-16-peptalk.md

NEW - news item

---

getting_started/nicolet.md

Updated information about Nicolet.

---

video.md

1st FieldTrip iEEG workshop at UC Davis (2019)

Added lecture by Bob Knight

---

workshop/toolkit2020.md

Alphabetically ordered. 
Added link to professional websites. 
P.S., Can't find the RU website for Hesham - he himself suggested his twitter page.

added tutor list 

---

example/irasa.md

Will have to complete this example script another time because of a bug in ft_sourceplot. These changes can be pulled in already.

extended IRASA example script to human ECoG data

---

faq/how_can_i_anonymize_an_anatomical_mri.md
faq/how_can_i_anonymize_fieldtrip_data.md
faq/how_can_i_change_the_head_localization_in_a_ctf_dataset.md
faq/how_can_i_check_the_quality_of_an_meeg_dataset.md
faq/itc.md

faq checks

---

example/how_to_incorporate_head_movements_in_meg_analysis.md

Reformatted matlab code that had turned into text

code reformatting

---

example/video_eeg.md

remark: example video should still be added.

added background information to the script

---

getting_started/yokogawa.md

Added example for making a channel layout + some explanation

added yokogawa channel layout example [#1737]

---

faq/how_can_i_anonymize_an_anatomical_mri.md

add description and code for combining defacing with brain segmentation to make sure the brain is not removed.

add combining defacing with brain segmentation

---

tutorial/eventrelatedstatistics.md

Now added as a note to the reader in the tutorial. Also proposed an FAQ page for it.

added TFCE method

---

_posts/2021-07-05-artinis-nirs.md
_posts/2021-07-09-artinis-nirs.md

This will appear under the "News and announcements" section on https://www.fieldtriptoolbox.org. 
Furthermore, a tweet will be sent from the https://twitter.com/fieldtriptoolbx account

add news item on Artinis fNIRS blog post

---

example/apply_cluster_and_analysis_on_tfrs_of_power_that_were_computed_with_besa.md
faq/how_can_i_define_neighbouring_sensors.md
faq/how_can_i_use_the_ivar_uvar_wvar_and_cvar_options_to_precisely_control_the_permutations.md
faq/what_is_the_idea_behind_statistical_inference_at_the_second-level.md
tutorial/cluster_permutation_timelock.md
tutorial/eventrelatedstatistics.md
video.md
workshop/natmeg/statistics.md

I made several corrections for the typos and links I encountered while going through the tutorials. Hope you find them useful.  
Thank you for the amazing tutorials and such an informative website!

Fix several typos &  links in the tutorials & faq

---

tutorial/sourcemodel.md

In step 3. Incorporate headshape information the code was unformatted due to missing whitespaces.
PS: I used the github facilities to create the PR and not manually forking, create a branch and then the PR.

FIX: fixed coding style

---

getting_started/eyelink.md

Updated the page, mainly:
[x] fixing some typos
[x] adding more detailed info on what values to use from the EyeLink .INI files
[x] suggesting to remove some outdated info

Updates to the Getting started with EyeLink page

---

tutorial/beamformer.md

Replace ft_redefinetrial by ft_selectdata (with cfg.latency)

Update beamformer.md: Replace ft_redefinetrial by ft_selectdata (with cfg.latency)

---

tutorial/eventrelatedaveraging.md

Replace ft_redefinetrial with ft_selectdata for selecting subsets of trials in "cleaning" section

Replace ft_redefinetrial with ft_selectdata

---

example/irasa.md

see PR #2089
1) tested with the new resample() function in #2087
2) updated 1/f simulation

updated simulation example and plot

---

faq/what_is_the_conductivity_of_the_brain_csf_skull_and_skin_tissue.md

as discussed with @robertoostenveld , I add here the online tool to compute conductivities of human tissues

add the online tool for conductivity calculation

---

example/threshold_free_cluster_enhancement.md

Happy you found my graphic helpful, I added a CC-BY attribution according to [creativecommons guidelines](https://wiki.creativecommons.org/wiki/best_practices_for_attribution#Attributing_an_image)

TFCE-Plot, added CC BY attribution

---

tutorial/parfor_eventrelatedaveraging.md

Tutorial on basic steps to use parallel computing when doing an analysis over multiple subjects

Add a parfor tutorial

---

example/ft_realtime_signalviewer.md

Minor edit. Fix typo in ft_realtime_signalviewer.md

---

development/module/fileio.md

Fixed MATLAB code used in ''Reading and writing of EEG/MEG time series data'' webpage.

Fixed MATLAB code

---

development/testing.md

- Listed all the tests that start with inspect_* and test_* 
- Improved memory sorting
- Corrected other minor mistakes
After these changes, I tried the tutorial myself and it runs smoothly.

Improved the code in testing.md

---

development/project/code_coverage.md

Added documentation on line-by-line code coverage using the unit test MATLAB framework

Code coverage

---

workshop/hamburg2023.md

This is the info of the Hamburg workshop that took place last November.

This is the announcment of the ws in Hamburg

---

workshop/sofia2024.md

HI, I just updated the schedule RE MBrainTrain involvement, and also refreshing the skills JM taught me :-) thanks

Updated the day and time of the hyperscanning session by MBrainTrain

---

example/electrodes2bem.md

Corrected the function name from warp_apply to ft_warp_apply in lines 43 to 45

Corrected function name
