- tutorial/human_ecog.md
removed a couple of apostrophes around "<" and ">" symbols, and fixed a few other text bugs
as a side note, note that some of the boxes containing code seem to have a slider but this slider does not work. this may be something to consider in the ongoing/future construction work of the new wiki
> format changes in human ecog tutorial

- tutorial/human_ecog.md
removed an obsolete quotation mark
not sure if this can be merged with the other PR I just did since this PR doesn't have the changes made in that PR? if not, please remove that quotation mark manually after pulling in the previous PR first
> human ecog tutorial

- workshop/madrid2019/tutorial_stats.md
the stats data had wrong name "freq_resting.mat" is the correct one instead of resting_freq.mat
I used the ~~~~ feature to make sure jekyll will interpret a specific line as code
I confirm again that both tutorial_freq and tutorial_stats run smoothly with the current fieldtrip's version
> data filename was wrong and fex small fixes

- tutorial/continuous.md
It seems the link has changed to lowercase erp.
> fix broken link in tutorial/continuous

- tutorial/automatic_artifact_rejection.md
Another portion of small fixes to the tutorials :)
two notes:
* on line `198` I changed double slash (`//`) to italics - I thought the intention was for the text to be the description of the image above it, and italics are used in such case in the tutorial. Whatever the intended purpose of these slashes was - the would show up in the html docs.
* on line `278` I change band pass frequecy limits to `[2 15]`, otherwise there was an error complaining about filter coefficient poles being outside unit circle. With `[2 15]` limits the blink artifacts are still well identifiable.
I also have one side note that might be better as a separate issue: the figure shown when looking for jump artifacts does look somewhat different than the one in the tutorial. The jump artifact on trial 18 is no longer …
> small fixes to tutorial/automatic_artifact_rejection/

- getting_started/egi.md
At least that is the directory name in `fieldtrip-20190224`.
(unfortunatelly both mff_v1 and mff_v2 do not work for me - I'll create an issue later)
> fixed path to java mff_v2 implementation

- faq/how_should_i_send_example_data_to_the_developers.md
Now that [GitHub lets free accounts have private repos](https://github.blog/2019-01-07-new-year-new-github/), Git LFS is a good way of sharing large example data sets between developers. It's especially useful because it can track file changes over time, and both the sender and receiver can check in changes, so it's good for iteratively working out bugs.
How about adding a section in the "How to send example data" FAQ for Git LFS & GitHub?
> Example data FAQ: add Git LFS as a sharing technique

- faq/how_should_i_send_example_data_to_the_developers.md
This PR updates or removes dead or non-http links on the "how to share experimental data" page. In particular, it removes the whole paragraph referencing a now-gone external "best ways to share large files" page.
> Cull dead links on "how to share data" FAQ

- development/realtime/biosemi.md
description for fixing problem with multi-EEG recordings (https://github.com/fieldtrip/fieldtrip/issues/974)
recompiled "biosemi2ft.exe" for x64 Windows: https://app.box.com/s/fzkc1z9s7wa6jt4qd1nvp577dl8npp14
> added fix description for Multi-EEG setup

- tutorial/memory.md
I've noticed a couple times that freq.cfg can get extremely big compared to the actual data in a freq struct. E.g. a struct array of 16 freq's was 162 MB, but after doing 
[freq.cfg] = deal([]); 
it was only 29 MB! ft_analysispipeline showed me a large number of cfg's for each run. I guess the reason is that ft_appenddata etc keeps the cfg of each single inputfiles...
> added Memory efficient coding tip

- tutorial/beamformer.md
One of the exercises in the beamforming tutorial references figures by numbers, however, somehow figure numbers have gotten lost. This pull request adds figure numbers back
> adding figure numbering

- _includes/cookie-banner
- assets/css/custom/_customstyles.scss
- index.md
This PR does 2 things:
- It improves compatibility of our cookie popup with certain browser extensions that people can use to manage their cookie permissions. The PR has no effect for people who do not use such extensions.
- It adds some very low-key styling to the release and news sections of the homepage, in order to make them a bit easier to parse visually.
> Cookiefix and news styling

- dataformat/meg.md
- getting_started/yokogawa.md
when trying to solve https://github.com/bids-standard/bids-specification/pull/653, I stumbled over a few typos here that I want to fix with this PR.
> FIX: typos in kit/yokogawa/ricoh documentation

- tutorial/sourcemodel.md
as discussed, I have tried here to incorporate an optional step during alignment that allows to take into account additional information on marker position such as polhemus data.
I did realize now, however, that the example data does not have polhemus data. There is a shape file that I am now using but this is more for visualization purpose of the interactive view and not so much a meaningful additional alignment step in this particular example (I believe the shape info is probably extracted from the MRI in the first place?)
When I adapted my pipeline for sourcemodel creation it was not straight forward how to include the polhemus data, so I think the instructions could be helpful to others as well, but I am afraid it does not fit well with the example data so maybe it is not a good …
> extra alignment step (polhemus) in sourcemodel tutorial 

- example/rereference.md
Dear @schoffelen and @robertoostenveld,
This pull request is connected to my other request for the introduction of [Laplacian rereferencing](https://github.com/fieldtrip/fieldtrip/pull/1600).
This is my first draft of the 'bipolar' and 'laplace' sections of the rereference example page.
Please let me know if you think something should be changed/added.
Moreover, should the reference I mentioned in the other pull request ([here](https://doi.org/10.1016/j.neuroimage.2018.08.020)) be added at the end of the example page?
Best,
Pietro Amerio
> Example page: bipolar and laplacian rereferencing

- faq/how_are_the_different_head_and_mri_coordinate_systems_defined.md
Related to comment in https://github.com/bids-standard/bids-specification/issues/747
> [ENH, MRG] Add scanner RAS coordinate frame definition

- tutorial/human_ecog.md
Updated original spatial normalization steps 26 and 27 of the protocol, superseding it by a single operation involving ft_electroderealign.
> Updated original spatial normalization steps 26 and 27

- getting_started/brainvision.md
I would like to share my code for translating the EEG data exported from BrainVision into a FieldTrip structure. Before that, the export data must be in a file .dat.
%% Case 1: you do not know if there are already markers in your dataset
cfg = [];
cfg.dataset = 'yourdataset.dat';
cfg.trialfun = 'ft_trialfun_general';
cfg.trialdef.eventtype = '?';
cfg = ft_definetrial(cfg);
% In addition to possible markers you put in your data while recording it, BrainVision always exports the data with an initial "New Segment" marker that signals the beginning of the recording. The function ft_deginetrial used as above should return at least one event found, with "New Segment" as event type.
%% Case 2, if there is only the "New Segment" marker
cfg = [];
cfg.dataset = 'yourdataset.dat';
cfg.trialfun = …
> Full code for importing BVA data

- getting_started/eeglab.md
I noticed that the fieldtrip2eeglab() version in fieldtrip/external is different from the one in the eeglab repository, but that's the topic for a different issue.
Thanks!
> Fix links to fieldtrip2eeglab()

- tutorial/timefrequencyanalysis.md
Fixes a typo in the Fieldtrip timefrequency analsis tutorial.
> fix typo in timefreq tutorial

- development/guideline/code.md
According to octave documentation, they do support anonymous functions, for quite a while now. And, the fieldtrip code is already using anonymous functions already. Therefor, remove the part in the guideline about not using inline (actually anonymous) functions.
> Remove part about octave no inline functions

- workshop/ni2_timefrequencyanalysis.md
I've made an adaptation of the timefrequencyanalysis tutorial, specific for use in the Neuroimaging 2 course (4th week SPED module). I've removed some redundancies, added some more details on multitapering and the relationship between wavelets and tapers, and made some further small changes to embed this nicely in the rest of the SPED module (e.g. default baseline correction to db). Also I added (additional) exercises and instructions for the students.
This file is not intended for general usage on the FT website (although the bit about multitapering "Multitapering as a hack around the time-frequency uncertainty principle?" may be insightful to some and I can add it to the general tutorial as well), but it would be convenient if we can host this page on the FT website.
@robertoostenveld …
> adding adapted TFR tutorial for NI2 course

- development/testing.md
- A clear explanation of the self-dependencies, direct and indirect dependencies is given.
- In the 'Finding tests' section, the user is advised to run the corresponding `test_ft_xxx` prior to generating a whole MATLAB table.
> Updated the testing webpage

- example/bids_eyetracker.md
- example/bids_meg.md
- example/bids_nirs.md
Some of the BIDS examples specify the `cfg.dataset_description.Authors` for multiple authors as one string rather than an array of strings.
This PR fixes that issue.
> convert multiple authors in str to array of strs

- workshop/cuttingeegx.md
- workshop/cuttingeegx/squids_vs_opms.md
- workshop/cuttingeegx/test_installation.md
See issue #798
@robertoostenveld it is ready to be sent to the participants. Please review and make the required changes as you see fit. I plan to send it today at 18:00.
> OPM tutorial for CuttingEEG X (2)

- workshop/nigeria2025/EEGexperiment_template.py
- workshop/nigeria2025/oddball_response_eeg.py
- workshop/nigeria2025/oddball_response_lslTriggers.py
- workshop/nigeria2025/stimuli.md
Updated the `Stimuli.md` tutorial page with examples for parallel and serial ports, incl. how to find the serial port address on Win and Mac.
I have also added example scripts for the auditory oddball experiment in two versions: one with parallel or serial triggers and one with LSL triggers. Also added the blank template script.
> add parallel/serial tigger tutorial and example PsyPy scripts
